# Generated by Django 3.2.5 on 2021-07-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('payment', models.PositiveIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('verificator_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
