# Generated by Django 3.2.5 on 2021-07-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
