# Generated by Django 3.2.5 on 2021-07-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210721_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='verificator_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
